<!DOCTYPE html>
<html lang="en">
<head>
  	<meta charset="utf-8">
  	<title>Dimitri Fourny | Windows C++ exceptions via SEH</title>
  	<meta name="viewport" content="width=device-width, initial-scale=1.0">
  	<meta name="description" content="Passionate security researcher.">
  	<meta name="author" content="Dimitri Fourny">
	
	<link href="/css/bootstrap.min.css" rel="stylesheet">
    <link href="/css/style.css" rel="stylesheet">
  	<link href="/css/syntax.css" rel="stylesheet">

    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
  	<link rel="shortcut icon" href="/img/favicon.png">
</head>

<body>
	<div class="navbar navbar-default navbar-static-top" role="navigation">
		<div class="container">
			<div class="navbar-header">
				<a class="navbar-brand" href="/">Dimitri Fourny</a>
	          	<button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
	            	<span class="icon-bar"></span>
	            	<span class="icon-bar"></span>
	            	<span class="icon-bar"></span>
	          	</button>
		    </div>

		    <div class="navbar-collapse collapse" id="navbar-main">
		      <ul class="nav navbar-nav navbar-right">
                <li class="active"><a href="/">Home</a></li>
                <li><a href="https://github.com/DimitriFourny">GitHub</a></li>
		        <li><a href="https://twitter.com/DimitriFourny">Twitter</a></li>
		        <li><a href="http://fr.linkedin.com/pub/dimitri-fourny/58/283/13a/">Linkedin</a></li>
		        <li><a href="/feed.xml">RSS</a></li>
		      </ul>
		    </div>
		</div>
	</div>

	<div class="container">
		
		<div class="row">
			<div class="col-sm-12">
				<h1 id="windows-c-exceptions-via-seh">Windows C++ exceptions via SEH</h1>

<p>The <a href="http://msdn.microsoft.com/fr-fr/library/windows/desktop/ms680657%28v=vs.85%29.aspx">Structured Exception Handling</a> (SEH) is used in Windows 
to manage the exceptions system. However, C++ use it to manage its own exceptions. We will make an example and study it in WinDbg to see how the exceptions are managed.</p>

<h2 id="source-code">Source code</h2>

<p>We will use a very simple source code to catch a divide by zero exception:</p>

<figure class="highlight"><pre><code class="language-cpp" data-lang="cpp"><span class="cp">#include &lt;iostream&gt;
#include &lt;stdexcept&gt;
</span>
<span class="kt">int</span> <span class="nf">divEx</span><span class="p">(</span><span class="kt">int</span> <span class="n">numerator</span><span class="p">,</span> <span class="kt">int</span> <span class="n">denominator</span><span class="p">)</span> <span class="p">{</span>
    <span class="k">if</span> <span class="p">(</span><span class="n">denominator</span> <span class="o">==</span> <span class="mi">0</span><span class="p">)</span> <span class="p">{</span>
        <span class="k">throw</span> <span class="n">std</span><span class="o">::</span><span class="n">overflow_error</span><span class="p">(</span><span class="s">"Divide by zero exception"</span><span class="p">);</span>
    <span class="p">}</span>

    <span class="k">return</span> <span class="n">numerator</span> <span class="o">/</span> <span class="n">denominator</span><span class="p">;</span>
<span class="p">}</span>

<span class="kt">int</span> <span class="nf">main</span><span class="p">()</span> <span class="p">{</span>
    <span class="kt">int</span> <span class="n">b</span> <span class="o">=</span> <span class="mi">0</span><span class="p">;</span>

    <span class="k">try</span> <span class="p">{</span>
        <span class="n">divEx</span><span class="p">(</span><span class="mh">0x42</span><span class="p">,</span> <span class="mi">0</span><span class="p">);</span> 
    <span class="p">}</span> <span class="k">catch</span><span class="p">(</span><span class="n">std</span><span class="o">::</span><span class="n">overflow_error</span> <span class="n">e</span><span class="p">)</span> <span class="p">{</span>
        <span class="n">std</span><span class="o">::</span><span class="n">cout</span> <span class="o">&lt;&lt;</span> <span class="s">"Error: "</span> <span class="o">&lt;&lt;</span> <span class="n">e</span><span class="p">.</span><span class="n">what</span><span class="p">();</span>
    <span class="p">}</span>

    <span class="k">return</span> <span class="mi">0</span><span class="p">;</span>
<span class="p">}</span></code></pre></figure>

<h2 id="exchain">!exchain</h2>

<p>SEH is just a chain list that we can read with the command !exchain:</p>

<figure class="highlight"><pre><code class="language-unknown" data-lang="unknown">0:000:x86&gt; !exchain
000000000018ff74: testseh!ILT+135(__except_handler4)+0 (000000000041108c)
000000000018ffcc: ntdll_775f0000!_except_handler4+0 (00000000776827e1)
000000000018ffe4: ntdll_775f0000!FinalExceptionHandlerPad21+0 (000000007762c9f3)</code></pre></figure>

<p>When the CPU will trigger an interruption, the kernel will browse the chain list and call the functions to try to “catch” the error.
If none function is designed to catch this error, the kernel will do the job himself (calling werfault or/and terminating the process).</p>

<p>Nevertheless, it can be usefull to know how the command <code>!exchain</code> get the full chain list. And it is pretty simple: <code>fs:[0]</code> contains a pointer on the chain list!</p>

<figure class="highlight"><pre><code class="language-unknown" data-lang="unknown">0:000:x86&gt; dd fs:[0]
0053:00000000  0018ff74

0:000:x86&gt; dt testseh!_EXCEPTION_REGISTRATION_RECORD 0x0018ff74 
   +0x000 Next             : 0x0018ffcc _EXCEPTION_REGISTRATION_RECORD
   +0x004 Handler          : 0x0041108c     _EXCEPTION_DISPOSITION  testseh!ILT+135(__except_handler4)+0
0:000:x86&gt; dt testseh!_EXCEPTION_REGISTRATION_RECORD 0x0018ffcc
   +0x000 Next             : 0x0018ffe4 _EXCEPTION_REGISTRATION_RECORD
   +0x004 Handler          : 0x776827e1     _EXCEPTION_DISPOSITION  ntdll_775f0000!_except_handler4+0
0:000:x86&gt; dt testseh!_EXCEPTION_REGISTRATION_RECORD 0x0018ffe4 
   +0x000 Next             : 0xffffffff _EXCEPTION_REGISTRATION_RECORD
   +0x004 Handler          : 0x7762c9d4     _EXCEPTION_DISPOSITION  ntdll_775f0000!FinalExceptionHandlerPad21+0</code></pre></figure>

<p>Oh and if you follow the last function (<code>FinalExceptionHandlerPad21</code>), you can find a very common message:</p>

<figure class="highlight"><pre><code class="language-unknown" data-lang="unknown">0:000:x86&gt; 
ntdll_775f0000!RtlUnhandledExceptionFilter2+0x72:
776ca7a9 689ceb6377      push    offset ntdll_775f0000! ?? ::FNODOBFM::`string' (7763eb9c)
776ca7ae 53              push    ebx
776ca7af 6a65            push    65h
776ca7b1 5e              pop     esi
776ca7b2 56              push    esi
776ca7b3 e83de6f8ff      call    ntdll_775f0000!DbgPrintEx (77658df5)
776ca7b8 83c418          add     esp,18h
776ca7bb e9fa010000      jmp     ntdll_775f0000!RtlUnhandledExceptionFilter2+0x283 (776ca9ba)
0:000:x86&gt; dc 7763eb9c
7763eb9c  2a200a0a 55202a2a 6e61686e 64656c64  .. *** Unhandled
7763ebac  63786520 69747065 30206e6f 38302578   exception 0x%08
7763ebbc  202c786c 20746968 25206e69 253a7377  lx, hit in %ws:%
7763ebcc  000a0a73 2a2a2a20 746e6520 2e207265  s... *** enter .
7763ebdc  20727865 66207025 7420726f 65206568  exr %p for the e
7763ebec  70656378 6e6f6974 63657220 0a64726f  xception record.
7763ebfc  2a209000 20202a2a 65746e65 632e2072  .. ***  enter .c
7763ec0c  25207278 6f662070 68742072 6f632065  xr %p for the co</code></pre></figure>

<h2 id="traditional-exception">Traditional exception</h2>

<p>Ok now we will begin to study the example. First of all, it will begin to add a function in the top of the SEH:</p>

<figure class="highlight"><pre><code class="language-unknown" data-lang="unknown">0:000:x86&gt; !exchain
000000000018ff74: testseh!ILT+135(__except_handler4)+0 (000000000041108c)
000000000018ffcc: ntdll_775f0000!wcstombs+87 (00000000776827e1)
000000000018ffe4: ntdll_775f0000!RtlCaptureContext+100 (000000007762c9f3)

00411730 55              push    ebp
00411731 8bec            mov     ebp,esp
00411733 6aff            push    0FFFFFFFFh
00411735 6888544100      push    offset testseh!std::operator&lt;&lt;&lt;std::char_traits&lt;char&gt; &gt;+0xf38 (00415488)
0041173a 64a100000000    mov     eax,dword ptr fs:[00000000h]
00411740 50              push    eax
00411741 64892500000000  mov     dword ptr fs:[0],esp

0:000:x86&gt; !exchain
000000000018ff28: testseh!std::operator&lt;&lt;&lt;std::char_traits&lt;char&gt; &gt;+f38 (0000000000415488)
000000000018ff74: testseh!ILT+135(__except_handler4)+0 (000000000041108c)
000000000018ffcc: ntdll_775f0000!wcstombs+87 (00000000776827e1)
000000000018ffe4: ntdll_775f0000!RtlCaptureContext+100 (000000007762c9f3)</code></pre></figure>

<p>After the initialization of SEH, it will call our function <code>divEx(0x42, 0)</code>:</p>

<figure class="highlight"><pre><code class="language-unknown" data-lang="unknown">0041176e 6a00            push    0
00411770 6a42            push    42h
00411772 e81dfbffff      call    testseh!ILT+655(?divExYAHHHZ) (00411294)</code></pre></figure>

<p>The check on the denominator will be done and it will call <code>CxxThrowException</code>:</p>

<figure class="highlight"><pre><code class="language-unknown" data-lang="unknown">0:000:x86&gt; u
testseh!divEx+0x1e [testseh\main.cpp @ 5]:
004114fe 837d0c00        cmp     dword ptr [ebp+0Ch],0              ; if (denominator == 0)
00411502 7521            jne     testseh!divEx+0x45 (00411525)
00411504 68007b4100      push    offset testseh!`string' (00417b00) ; "Divide by zero exception"
00411509 8d8d30ffffff    lea     ecx,[ebp-0D0h]
0041150f e88ffdffff      call    testseh!ILT+670(??0overflow_errorstdQAEPBDZ) (004112a3)
00411514 68c08d4100      push    offset testseh!_TI3?AVoverflow_errorstd (00418dc0)
00411519 8d8530ffffff    lea     eax,[ebp-0D0h]
0041151f 50              push    eax
00411520 e874fdffff      call    testseh!ILT+660(__CxxThrowException (00411299)
00411525 8b4508          mov     eax,dword ptr [ebp+8]</code></pre></figure>

<p><code>CxxThrowException</code> is referenced <a href="http://msdn.microsoft.com/en-us/library/ff795730.aspx">in the msdn</a>: “Builds the exception record and calls the runtime environment to start processing the exception”.
All the structures are known:</p>

<figure class="highlight"><pre><code class="language-cpp" data-lang="cpp"><span class="kt">void</span> <span class="kr">__stdcall</span> <span class="n">_CxxThrowException</span><span class="p">(</span>
   <span class="kt">void</span><span class="o">*</span> <span class="n">pExceptionObject</span>   <span class="c1">// 0018fd64
</span>   <span class="n">_ThrowInfo</span><span class="o">*</span> <span class="n">pThrowInfo</span>   <span class="c1">// 00418dc0 
</span><span class="p">);</span></code></pre></figure>

<figure class="highlight"><pre><code class="language-unknown" data-lang="unknown">0:000:x86&gt; dt -r4 testseh!_s__ThrowInfo 00418dc0
   +0x000 attributes       : 0
   +0x004 pmfnUnwind       : 0x00411244     void  testseh!ILT+575(??1overflow_errorstdUAEXZ)+0
   +0x008 pForwardCompat   : (null) 
   +0x00c pCatchableTypeArray : 0x00418e2c _s__CatchableTypeArray
      +0x000 nCatchableTypes  : 0n3
      +0x004 arrayOfCatchableTypes : [0] 0x00418e98 _s__CatchableType
         +0x000 properties       : 0
         +0x004 pType            : 0x0041a000 _TypeDescriptor
            +0x000 pVFTable         : 0x00417840 Void
            +0x004 spare            : (null) 
            +0x008 name             : [0]  ".?AVoverflow_error@std@@"
         +0x008 thisDisplacement : _PMD
            +0x000 mdisp            : 0n0
            +0x004 pdisp            : 0n-1
            +0x008 vdisp            : 0n0
         +0x014 sizeOrOffset     : 0n12
         +0x018 copyFunction     : 0x00411271           void  testseh!ILT+620(??0overflow_errorstdQAEABV01Z)+0</code></pre></figure>

<p>After that, <code>CxxThrowException</code> will call <code>NtRaiseException</code>:</p>

<figure class="highlight"><pre><code class="language-unknown" data-lang="unknown">7762c7a0 e8bbf1ffff      call    ntdll_775f0000!NtRaiseException (7762b960)

0:000:x86&gt; u NtRaiseException
ntdll_775f0000!NtRaiseException:
7762b960 b846010000      mov     eax,146h
7762b965 64ff15c0000000  call    dword ptr fs:[0C0h]
7762b96c c20c00          ret     0Ch

0:000:x86&gt; u poi(fs:[0c0h])
wow64cpu!KiFastSystemCall:
775211d8 eaa42152773300  jmp     0033:775221A4</code></pre></figure>

<p><code>NtRaiseException</code> will call <code>KiRaiseException</code> but today we will not go into the kernel.
Now the kernel will call the first function in the SEH and we will follow the flow:</p>

<figure class="highlight"><pre><code class="language-unknown" data-lang="unknown">0:000:x86&gt; !exchain
000000000018ff28: testseh!std::operator&lt;&lt;&lt;std::char_traits&lt;char&gt; &gt;+f38 (0000000000415488)

0:000:x86&gt; u 00415488
testseh!std::operator&lt;&lt;&lt;std::char_traits&lt;char&gt; &gt;+0xf38:
00415488 b810904100      mov     eax,offset testseh!_CT??_R0?AVruntime_errorstd+0x148 (00419010)
0041548d e94ebdffff      jmp     testseh!ILT+475(___CxxFrameHandler3) (004111e0)
0:000:x86&gt; u 
testseh!ILT+475(___CxxFrameHandler3):
004111e0 e9ff0f0000      jmp     testseh!_CxxFrameHandler3 (004121e4)
0:000:x86&gt; u 
MSVCR100D!__CxxFrameHandler3+0x27:
584f9c07 e8d4070000      call    MSVCR100D!__InternalCxxFrameHandler (584fa3e0)
0:000:x86&gt; u 
MSVCR100D!__FrameUnwindToState+0x1b4:
584fae64 e827060000      call    MSVCR100D!__BuildCatchObject (584fb490)
0:000:x86&gt; u
MSVCR100D!__FrameUnwindToState+0x240:
584faef0 e8cbebffff      call    MSVCR100D!_JumpToContinuation (584f9ac0)
0:000:x86&gt; u
MSVCR100D!__FrameUnwindToState+0x312:
584fafc2 e899ecffff      call    MSVCR100D!_CallCatchBlock2 (584f9c60)
0:000:x86&gt; u
MSVCR100D!_CallCatchBlock2+0x56:
584f9cb6 e8353a0000      call    MSVCR100D!_CallSettingFrame (584fd6f0)
0:000:x86&gt; u 
MSVCR100D!_CallSettingFrame+0x25:
584fd715 ffd0            call    eax</code></pre></figure>

<p>Surprisingly (or not), we will enter in the subprogram “catch”:</p>

<figure class="highlight"><pre><code class="language-unknown" data-lang="unknown">00411782 8d4de0          lea     ecx,[ebp-20h]
00411785 ff15c4b34100    call    dword ptr [testseh!_imp_?whatexceptionstdUBEPBDXZ (0041b3c4)] ; std::overflow_error.what()
0041178b 3bf4            cmp     esi,esp
0041178d e80dfaffff      call    testseh!ILT+410(__RTC_CheckEsp) (0041119f)
00411792 50              push    eax
00411793 68b4784100      push    offset testseh!`string' (004178b4) ; "Error: "
00411798 a104b34100      mov     eax,dword ptr [testseh!_imp_?coutstd (0041b304)]
0041179d 50              push    eax
0041179e e8b6f9ffff      call    testseh!ILT+340(??$?6U?$char_traitsDstdstdYAAAV?$basic_ostreamDU?$char_traitsDstd (00411159)
004117a3 83c408          add     esp,8
004117a6 50              push    eax
004117a7 e8adf9ffff      call    testseh!ILT+340(??$?6U?$char_traitsDstdstdYAAAV?$basic_ostreamDU?$char_traitsDstd (00411159) ; std::cout
004117ac 83c408          add     esp,8
004117af c645fc01        mov     byte ptr [ebp-4],1 
004117b3 8d4de0          lea     ecx,[ebp-20h]
004117b6 e889faffff      call    testseh!ILT+575(??1overflow_errorstdUAEXZ) (00411244) ; std::overflow_error::~overflow_error</code></pre></figure>

<p>Tada! We have catched this error!</p>

<h2 id="crash-dump">Crash dump</h2>

<p>When you have understood the basics, it is possible to make some usefull things like a system to catch all exceptions:</p>

<figure class="highlight"><pre><code class="language-cpp" data-lang="cpp"><span class="cp">#include &lt;windows.h&gt;
</span>
<span class="n">LONG</span> <span class="nf">topSEH</span><span class="p">(</span><span class="k">struct</span> <span class="n">_EXCEPTION_RECORD</span><span class="o">*</span> <span class="n">ExceptionRecord</span><span class="p">,</span> <span class="kt">void</span><span class="o">*</span> <span class="n">EstablisherFrame</span><span class="p">,</span> <span class="k">struct</span> <span class="n">_CONTEXT</span><span class="o">*</span> <span class="n">ContextRecord</span><span class="p">,</span> <span class="kt">void</span><span class="o">*</span> <span class="n">DispatcherContext</span><span class="p">)</span> <span class="p">{</span>
    <span class="n">OutputDebugStringA</span><span class="p">(</span><span class="s">"Gotta Catch 'Em All!</span><span class="se">\n</span><span class="s">"</span><span class="p">);</span>
    <span class="k">return</span> <span class="n">EXCEPTION_EXECUTE_HANDLER</span><span class="p">;</span>
<span class="p">}</span>

<span class="kt">int</span> <span class="nf">main</span><span class="p">()</span> <span class="p">{</span>
    <span class="kt">int</span> <span class="n">b</span> <span class="o">=</span> <span class="mi">0</span><span class="p">;</span>

    <span class="kr">__asm</span> <span class="p">{</span>
        <span class="n">push</span>    <span class="n">topSEH</span>
        <span class="n">mov</span>     <span class="n">eax</span><span class="p">,</span> <span class="n">dword</span> <span class="n">ptr</span> <span class="n">fs</span><span class="o">:</span><span class="p">[</span><span class="mi">0</span><span class="p">]</span>
        <span class="n">push</span>    <span class="n">eax</span>
        <span class="n">mov</span>     <span class="n">dword</span> <span class="n">ptr</span> <span class="n">fs</span><span class="o">:</span><span class="p">[</span><span class="mi">0</span><span class="p">],</span> <span class="n">esp</span>
    <span class="p">}</span>

    <span class="kt">int</span> <span class="n">a</span> <span class="o">=</span> <span class="mi">42</span> <span class="o">/</span> <span class="n">b</span><span class="p">;</span>

    <span class="k">return</span> <span class="mi">0</span><span class="p">;</span>
<span class="p">}</span></code></pre></figure>

<figure class="highlight"><pre><code class="language-unknown" data-lang="unknown">0:000:x86&gt; g
Gotta Catch 'Em All!
(153c.1538): Integer divide-by-zero - code c0000094 (!!! second chance !!!)
testseh!main+0x3e:
0041142e f77df8          idiv    eax,dword ptr [ebp-8] ss:002b:0018ff2c=00000000
0:000:x86&gt; !exchain
000000000018fe48: testseh!ILT+455(?topSEHYAJPAU_EXCEPTION_RECORDPAXPAU_CONTEXT+0 (00000000004111cc)
000000000018ff74: testseh!ILT+105(__except_handler4)+0 (000000000041106e)
000000000018ffcc: ntdll_775f0000!wcstombs+87 (00000000776827e1)
000000000018ffe4: ntdll_775f0000!RtlCaptureContext+ea (000000007762c9dd)</code></pre></figure>

<p>It is possible to do something like this too with the <a href="http://msdn.microsoft.com/en-us/library/windows/desktop/ms681420%28v=vs.85%29.aspx">Vectored Exception Handling</a>.</p>


			</div>
		</div>

    </div>

</body>
</html>
